services:
  mysql:
    image: mysql:8.0.22
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=testdb3
    volumes:
      - amos_p1_volume:/var/lib/mysql

volumes:
  amos_p1_volume:
    external: false