# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ production ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file backend/pom.xml -Dmaven.test.skip=true 
    - name: Build docker backend 
      run: docker build -t ${{secrets.DOCKER_ID}}/backend backend
    - name: Build docker frontend 
      run: docker build -t ${{secrets.DOCKER_ID}}/frontend Frontend
    - name: docker login with secret
      run: docker login -u ${{secrets.DOCKER_ID}} -p ${{secrets.DOCKER_PW}}
    - name: docker push backend and frontend to dockerhub (create incremental counter)
      run: docker push ${{secrets.DOCKER_ID}}/backend
    - name: push frontend to dockerhub
      run: docker push ${{secrets.DOCKER_ID}}/frontend
